name: Google Play App Monitor

on:
  schedule:
    # 每 20 分钟运行一次 (UTC 时间)
    - cron: "*/20 * * * *"
  workflow_dispatch:          # 保留手动触发按钮

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # 开启缓存以加速执行并节省额度
          cache: 'pip'

      - name: Install dependencies
        run: pip install requests

      - name: Run checker
        run: python check_app.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
